In [6]:
import numpy as np
import functools as ft

In [7]:
pauli_Z = np.array([1, 0, 0, -1]).reshape([2, 2])
pauli_X = np.array([0, 1, 1, 0]).reshape([2, 2])
pauli_Y = np.array([0, -1j, 1j, 0]).reshape([2, 2])

_eigenvalues, _eigenvectors = np.linalg.eig(pauli_Z)
H = _eigenvectors[0]
V = _eigenvectors[1]

_eigenvalues, _eigenvectors = np.linalg.eig(pauli_X)
D = _eigenvectors[0]
A = _eigenvectors[1]

_eigenvalues, _eigenvectors = np.linalg.eig(pauli_Y)
R = _eigenvectors[0]
L = _eigenvectors[1]

Below is an example of how to call a function that acts iteratively on the arguments, similar to how mapping works in mathematica.

In [10]:
args = [np.arange(2), np.arange(2,4)]
np.kron(*args)

array([0, 0, 2, 3])

Could write something clever for calling the Kron of basis vectors. Need to make the basis vectors a dictionary, in order to call something from a string. Think thats the cleanest way to go, rather than bulk editting HH, HV, VH, VV, DD, DA etc...

In [11]:
Bell = {
    "Psi Minus": (1/np.sqrt(2))*(np.kron(H,V) - np.kron(V,H)),
    "Psi Plus": (1/np.sqrt(2))*(np.kron(H,V) + np.kron(V,H)),
    "Phi Plus": (1/np.sqrt(2))*(np.kron(H,H) + np.kron(V,V)),
    "Phi Minus": (1/np.sqrt(2))*(np.kron(H,H) - np.kron(V,V))
}

In [8]:
Bell["Psi Minus"]

array([ 0.        ,  0.70710678, -0.70710678,  0.        ])

In [9]:
np.kron(H,H)

array([1., 0., 0., 0.])

In [13]:
_args = [H, H]
np.kron(*_args)

array([1., 0., 0., 0.])

Writing a function which can perform the Kronecker delta on more than two arguments, run through a quick example first.

In [18]:
_args = [H, H, H, H]

ft.reduce(lambda x, y: np.kron(x, y), _args)

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

The ft.reduce function is roughly equivalent to the following lines of code. Additionally, I define kronk, which will take the Kronecker product of a list of inputs

In [16]:
def reduce(function, iterable, initializer = None):
    it = iter(iterable)
    if initializer is None:
        value = next(it)
    else:
        value = initializer
    for element in it:
        value = function(value, element)
    return value

def kronk(iterable):
    return reduce(np.kron, iterable)

In [19]:
reduce(np.kron, _args)

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
kronk([H,V,H])

array([0., 0., 1., 0., 0., 0., 0., 0.])

The below generates a GHZ state of arbitrary dimensions by calling GHZ(n) where n is the dimension of the state

In [46]:
def GHZ(dimension):

    _basis_vector_H = []
    _basis_vector_V = []
    _basis_vectors = [H, V]
    
    for i in range(dimension):
        _basis_vector_H.append(_basis_vectors[0])
        _basis_vector_V.append(_basis_vectors[1])

    
    return 1/np.sqrt(2)*(reduce(np.kron, _basis_vector_H) + reduce(np.kron, _basis_vector_V))


In [50]:
GHZ(4)

array([0.70710678, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.70710678])